on:
  push:
    branches: main

jobs:
  AL:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Run apt-get
        run: |
          sudo apt-get update
      - name: Install libcurl
        run: |
          sudo apt-get install libcurl4-openssl-dev
      - name: Install redland dep
        run: |
          sudo apt-get install librdf0-dev
      - name: Install sodium dep
        run: |
          sudo apt-get install libsodium-dev
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Dependencies
        uses: r-lib/actions/setup-renv@v2
      - name: Set state
        run: Rscript -e 'state_to_use <- "AL"'
      - name: Generate state database
        run: Rscript -e 'source("scripts/01-state-by-state/AL-state-parquet.R")'
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AL
          path: data/parquet/*

