on:
  push:
    branches: add-annual-carbon-good

jobs:
  CO:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Run apt-get
        run: |
          sudo apt-get update
      - name: Install libcurl
        run: |
          sudo apt-get install libcurl4-openssl-dev
      - name: Install redland dep
        run: |
          sudo apt-get install librdf0-dev
      - name: Install sodium dep
        run: |
          sudo apt-get install libsodium-dev
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Dependencies
        uses: r-lib/actions/setup-renv@v2
      - name: Set state
        run: Rscript -e 'state_to_use <- "CO"'
      - name: Generate state database
        run: Rscript -e 'source("scripts/01-state-by-state/CO-state-parquet.R")'
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CO
          path: data/parquet/*
  NH:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Run apt-get
        run: |
          sudo apt-get update
      - name: Install libcurl
        run: |
          sudo apt-get install libcurl4-openssl-dev
      - name: Install redland dep
        run: |
          sudo apt-get install librdf0-dev
      - name: Install sodium dep
        run: |
          sudo apt-get install libsodium-dev
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Dependencies
        uses: r-lib/actions/setup-renv@v2
      - name: Set state
        run: Rscript -e 'state_to_use <- "NH"'
      - name: Generate state database
        run: Rscript -e 'source("scripts/01-state-by-state/NH-state-parquet.R")'
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NH
          path: data/parquet/*
  WI:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Run apt-get
        run: |
          sudo apt-get update
      - name: Install libcurl
        run: |
          sudo apt-get install libcurl4-openssl-dev
      - name: Install redland dep
        run: |
          sudo apt-get install librdf0-dev
      - name: Install sodium dep
        run: |
          sudo apt-get install libsodium-dev
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Dependencies
        uses: r-lib/actions/setup-renv@v2
      - name: Set state
        run: Rscript -e 'state_to_use <- "WI"'
      - name: Generate state database
        run: Rscript -e 'source("scripts/01-state-by-state/WI-state-parquet.R")'
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: WI
          path: data/parquet/*
  stack:
    runs-on: ubuntu-latest
    needs: [CO, NH, WI]
    env:
      ZENODO_TOKEN: ${{ secrets.ZENODO_TOKEN }}
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Run apt-get
        run: |
          sudo apt-get update
      - name: Install libcurl
        run: |
          sudo apt-get install libcurl4-openssl-dev
      - name: Install redland dep
        run: |
          sudo apt-get install librdf0-dev
      - name: Install sodium dep
        run: |
          sudo apt-get install libsodium-dev
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Dependencies
        uses: r-lib/actions/setup-renv@v2
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: data/parquet
          merge-multiple: true
      - name: Stack files
        run: Rscript -e 'source("scripts/02-create_db_from_parquet.R")'
      - name: Push to Zenodo
        run: Rscript -e 'source("scripts/03-upload_parquet_db_zenodo.R")'
      - name: Check db
        run: Rscript -e 'source("scripts/04-check_db.R")'
      - name: Check saplings
        run: Rscript -e 'source("scripts/05-check_saplings.R")'
      - name: Check annualized
        run: Rscript -e 'source("scripts/06-check-annualized.R")'
