on:
  push:
    branches: toy-artifacts

jobs:
  CT:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyr
            any::duckdb
            any::arrow
            any::here
            any::DBI
            any::stringr
            any::purrr
            any::dbplyr
            any::boxr
            any::jose
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up directories
        run: Rscript -e 'source("scripts/01-state-by-state/CT-state-parquet.R")'
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CT
          path: data/parquet/*
  stack:
    runs-on: ubuntu-latest
    needs: [CT]
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyr
            any::duckdb
            any::arrow
            any::here
            any::DBI
            any::stringr
            any::purrr
            any::dbplyr
            any::boxr
            any::jose
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: data/parquet
          merge-multiple: true
      - name: Stack files
        run: Rscript -e 'source("scripts/02-create_db_from_parquet.R")'